/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package gui;

import dao.OrderDAO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;



import java.awt.BorderLayout;

/**
 *
 * @author zeljk
 */
public class AdminForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminForm.class.getName());
    JTable table;
    DefaultTableModel model;
    JButton btnDetails = new JButton("Detalji porudzbine");
    /** Creates new form AdminForm */
    public AdminForm() {
        initComponents();
        setTitle("Admin - pregled porudzbine");
        setSize(600, 350);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(242,235,216));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        getContentPane().setLayout(new java.awt.BorderLayout());
        
        //KOLONE
        List<String> columns = new ArrayList<>();
        columns.add("ID");
        columns.add("Datum");
        columns.add("Ukupno");
        columns.add("Korisnik");
        
        //PODACI
        List<List<Object>> data = OrderDAO.getAllOrders();
        
        model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false; //tabela je samo za pregled
            }
        };
        
        model.setColumnIdentifiers(columns.toArray());
        
        for (List<Object> row : data){
            model.addRow(row.toArray());
        }
        
        table = new JTable(model);
        
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        //TABELA
        getContentPane().add(new JScrollPane(table), java.awt.BorderLayout.CENTER);
        
        //DONJI PANEL SA DUGMETOM
        JPanel bottomPanel = new JPanel();
        bottomPanel.add(btnDetails);
        getContentPane().add(bottomPanel, BorderLayout.SOUTH);
        
        //AKCIJA DUGMETA
        btnDetails.addActionListener(e -> openOrderDetails());
    }
    
    void openOrderDetails(){
        int selectedRow = table.getSelectedRow();
        
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Morate selektovati porudzbinu!", "Upozorenje!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int orderId = (int) model.getValueAt(selectedRow, 0);
        new OrderDetailsForm(orderId).setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
                if ("Nimbus".equals(info.getName())){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch(Exception ex){
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        
        
        java.awt.EventQueue.invokeLater(() -> new AdminForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
