/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.*;

/**
 *
 * @author zeljk
 */
public class MainForm extends javax.swing.JFrame {
    


    /**
     * Creates new form MainForm
     * @param role
     */
    public MainForm(String role) {
        initComponents();
        setTitle("Picerija");
        setSize(300,200);
        setLayout(null);
        getContentPane().setBackground(new java.awt.Color(242,235,216));
        
        JButton btnOrder = new JButton("Nova porudzbina");
        btnOrder.setBounds(50,50,200,30);
        add(btnOrder);
        
        btnOrder.addActionListener(e -> new OrderForm().setVisible(true));
        
        if(role.equals("ADMIN")){
            JButton btnAdmin = new JButton("Admin pregled");
            btnAdmin.setBounds(50,100,200,30);
            add(btnAdmin);
            
            btnAdmin.addActionListener(e -> new AdminForm().setVisible(true));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
