/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.OrderDAO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
/**
 *
 * @author zeljk
 */
public class OrderDetailsForm extends javax.swing.JFrame {
    
    //private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderDetailsForm.class.getName());

    /**
     * Creates new form OrderDetailsForm
     */
    
    JTable table;
    DefaultTableModel model;
    private int orderId;
    
    public OrderDetailsForm(int orderId) {
        this.orderId=orderId;
        initComponents();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        setTitle("Detalji porudzbine #" + orderId);
        setSize(400,300);
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(242,235,216));
        
        setLayout(new java.awt.BorderLayout());
        
        model = new DefaultTableModel(
        new Object[]{"Pizza", "Kolicina", "Cena", "Ukupno"}, 0);
        table = new JTable(model);
        
        add(new JScrollPane(table), java.awt.BorderLayout.CENTER);
        
        loadItems(orderId);
        
        revalidate();
        repaint();
    }
    
    private void loadItems(int orderId){
        try {
            ResultSet rs = OrderDAO.getOrderItems(orderId);
            while(rs.next()){
                model.addRow(new Object []{
                    rs.getString("name"),
                    rs.getInt("quantity"),
                    rs.getDouble("price"),
                    rs.getDouble("total")
                });
            }
        } catch (Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
