/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.OrderDAO;
import dao.PizzaDAO;
import java.awt.Image;
import model.Pizza;


import javax.swing.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zeljk
 */
public class OrderForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderForm.class.getName());

    JComboBox<Pizza> cbPizza = new JComboBox<>();
    JTextField txtQty = new JTextField();
    JLabel lblTotal = new JLabel("0.0");
    
    JButton btnAdd = new JButton("Dodaj pizzu");
    JButton btnSave = new JButton("Sačuvaj porudzbinu");
    
    JTable table;
    DefaultTableModel model;
   
    /**
     * Creates new form OrderForm
     */
    public OrderForm() {
        initComponents();
        
       
        setTitle("Nova porudzbina");
        setSize(520,380);
        setLayout(null);
        
        setLocationRelativeTo(null);
        
        getContentPane().setBackground(new java.awt.Color(242,235,216));
        
       /* ImageIcon logoIcon = new ImageIcon(getClass().getResource("/resources/Logo.png"));
        JLabel lblLogo = new JLabel(logoIcon);
        lblLogo.setBounds(80, 5, 150, 60);
        add(lblLogo);*/
       java.net.URL imageUrl = getClass().getResource("/resources/Logo.png");

if (imageUrl != null) {
    ImageIcon originalIcon = new ImageIcon(imageUrl);
    
    
    Image scaledImage = originalIcon.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
    
   
    ImageIcon logoIcon = new ImageIcon(scaledImage);
    
    JLabel lblLogo = new JLabel(logoIcon);
    lblLogo.setBounds(200, 240, 100, 100); // Ovde postavljate poziciju i veličinu labele
    add(lblLogo);
} else {
    System.out.println("Greška: Slika nije pronađena!");
}
        
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        add(new JLabel("Pizza")).setBounds(20,30,80,25);
        add(cbPizza).setBounds(100,20,150,25);
        
        add(new JLabel("Kolicina")).setBounds(20,60,80,25);
        add(txtQty).setBounds(100,60,150,25);
        
        add(btnAdd).setBounds(270, 40, 200, 30);
        
        //TABELA
        model = new DefaultTableModel(
                new Object[]{"Pizza ID", "Pizza", "Kolicina", "Cena","Ukupno"}, 0
        );
        table = new JTable(model);
        
        JScrollPane sp = new JScrollPane(table);
        add(sp).setBounds(20,110,450,140);
        
        //DONJI DIO
        add(new JLabel("Ukupno")).setBounds(20,270,80,25);
        add(lblTotal).setBounds(100,270,150,25);
        
        add(btnSave).setBounds(300,270,170,30);
        
        loadPizzas();
        
        btnAdd.addActionListener(e -> addItem());
        btnSave.addActionListener(e -> saveOrder());
        
        
       
    }
    
    private void loadPizzas(){
        List<Pizza> list = PizzaDAO.getAll();
        for (Pizza p : list) cbPizza.addItem(p);
    }
    
    void addItem(){
        Pizza p = (Pizza) cbPizza.getSelectedItem();
        int qty = Integer.parseInt(txtQty.getText());
        
        double subtotal = p.getPrice()* qty;
        
        model.addRow(new Object[]{
            p.getId(),
            p.getName(),
            qty,
            p.getPrice(),
            subtotal
        });
        
        updateTotal();
        txtQty.setText("");
    }
    
    void updateTotal(){
        double sum = 0;
        for (int i = 0; i < model.getRowCount(); i++){
            sum += (double) model.getValueAt(i, 4);
        }
        lblTotal.setText(String.valueOf(sum));
    }
    
    void saveOrder(){
      double total = Double.parseDouble(lblTotal.getText());
      
      int userId = LoginForm.loggedUser.getId();
      int orderId = OrderDAO.createOrder(userId, total);
      
      for (int i = 0; i < model.getRowCount(); i++){
          int pizzaId = (int) model.getValueAt(i, 0);
          int qty = (int) model.getValueAt(i, 2);
          double price = (double) model.getValueAt(i, 3);
          
          OrderDAO.addItem(orderId, pizzaId, qty, price);
      }
      
      JOptionPane.showMessageDialog(this, "Porudzbina je sacuvana!");
      dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OrderForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
